/**
 * Per-slug aspect ratio (`width / height`) parsed from each
 * normalized SVG's `viewBox`. Generated by `scripts/gen:logos.ts`,
 * committed to `public/logo/manifest.json`, imported as a JSON module
 * by the SSR loader.
 *
 * Logos render at fixed heights (22 / 60 px), so only the ratio is
 * needed to size the `<img>` and reserve horizontal space — the
 * rendered width is `Math.round(height * ratio)` at the call site.
 */
export type LogoManifest = Record<string, number>
