import * as fs from 'node:fs/promises'
import * as path from 'node:path'
import * as Svg from './svg.js'

const root = path.resolve(import.meta.dirname, '../..')
const sourceDir = path.join(root, 'public/logos/raw')
const colorDir = path.join(root, 'public/logos')
const monoDir = path.join(root, 'public/logos/mono')
const manifestPath = path.join(colorDir, 'manifest.json')

/**
 * Per-slug aspect ratio (`width / height`) parsed from each
 * normalized SVG's `viewBox`. Logos render at fixed heights (22 / 60
 * px), so only the ratio is needed to size the `<img>` and reserve
 * horizontal space — the rendered width is `Math.round(height *
 * ratio)` at the call site.
 *
 * Generated by {@link run}, written to `public/logos/manifest.json`,
 * and imported as a JSON module by the SSR loader and worker.
 * Mono and color outputs share the same aspect ratio (same
 * viewBox-retargeting), so one manifest covers both.
 */
export type Manifest = Record<string, number>

/**
 * Generate normalized logo SVGs from `public/logos/raw/` into two
 * sibling output dirs:
 *
 * - `public/logos/mono/` — single-ink mask (page recolors via CSS).
 * - `public/logos/`      — colored, brand-native palette (used by
 *                          server-rendered images, e.g. the planned
 *                          `/sponsors.{ext}` route).
 *
 * Both pass through identical SVGO cleanup + viewBox re-targeting, so
 * the resulting aspect ratios match. The shared `manifest.json` lives
 * at the top level (`public/logos/manifest.json`) and is the source of
 * truth for both variants.
 *
 * Every committed source becomes one mono + one color output; slugs
 * with no source are silently absent (the homepage falls back to a
 * plain-text label). The mono dir is wiped each run; for the color
 * outputs at the top level we delete only the previously-emitted
 * `*.svg` files so we don't blow away `raw/`, `mono/`, or
 * `manifest.json`.
 *
 * Pure file-IO — no KV, no edge cache, no network. The CI workflow
 * commits the result back to the repo.
 */
export async function run(): Promise<void> {
  const entries = await fs.readdir(sourceDir, { withFileTypes: true })

  // Wipe `mono/` wholesale; for the top-level color outputs we only
  // delete loose `*.svg` files (preserves `raw/` + `mono/` siblings).
  await fs.rm(monoDir, { recursive: true, force: true })
  await fs.mkdir(monoDir, { recursive: true })
  for (const entry of await fs.readdir(colorDir, { withFileTypes: true }))
    if (entry.isFile() && entry.name.endsWith('.svg')) await fs.rm(path.join(colorDir, entry.name))

  const manifest: Manifest = {}
  for (const entry of entries) {
    if (!entry.isFile() || !entry.name.endsWith('.svg')) continue
    const slug = entry.name.slice(0, -'.svg'.length)
    const bytes = await fs.readFile(path.join(sourceDir, entry.name), 'utf-8')
    let mono: string
    let color: string
    try {
      mono = await Svg.transform(bytes, { mode: 'mono' })
      color = await Svg.transform(bytes, { mode: 'color' })
    } catch (error) {
      // unparseable / un-rasterizable source SVG — log + skip so one
      // bad input doesn't sink the whole run.
      console.error('logo SVG transform failed:', slug, error)
      continue
    }
    const box = parseViewBox(mono)
    if (!box) {
      console.error('logo viewBox parse failed:', slug)
      continue
    }
    manifest[slug] = box.width / box.height
    await fs.writeFile(path.join(monoDir, `${slug}.svg`), mono, 'utf-8')
    await fs.writeFile(path.join(colorDir, `${slug}.svg`), color, 'utf-8')
  }

  // sorted-by-key for stable diffs across runs
  const sorted: Manifest = {}
  for (const slug of Object.keys(manifest).sort()) sorted[slug] = manifest[slug]!
  await fs.writeFile(manifestPath, `${JSON.stringify(sorted, null, 2)}\n`, 'utf-8')
}

/**
 * Pull width + height out of an SVG's `viewBox` (or `width`/`height`
 * attributes as a fallback). Returns `null` when no usable size can
 * be recovered. Regex-based — a full XML parser is overkill for the
 * SVGO-cleaned bytes {@link Svg.transform} emits.
 */
function parseViewBox(svg: string): { width: number; height: number } | null {
  const viewBox = svg.match(
    /\bviewBox\s*=\s*["']\s*([-\d.eE+]+)\s+([-\d.eE+]+)\s+([-\d.eE+]+)\s+([-\d.eE+]+)\s*["']/,
  )
  if (viewBox) {
    const width = Number(viewBox[3])
    const height = Number(viewBox[4])
    if (width > 0 && height > 0) return { width, height }
  }
  const w = svg.match(/<svg\b[^>]*\bwidth\s*=\s*["']\s*([\d.]+)/)?.[1]
  const h = svg.match(/<svg\b[^>]*\bheight\s*=\s*["']\s*([\d.]+)/)?.[1]
  if (w && h) {
    const width = Number(w)
    const height = Number(h)
    if (width > 0 && height > 0) return { width, height }
  }
  return null
}
