import * as fs from 'node:fs/promises'
import * as path from 'node:path'
import * as Svg from './svg.js'

const root = path.resolve(import.meta.dirname, '../..')
const sourceDir = path.join(root, 'public/logos')
const outputDir = path.join(root, 'public/logos/mono')
const manifestPath = path.join(outputDir, 'manifest.json')

/**
 * Per-slug aspect ratio (`width / height`) parsed from each
 * normalized SVG's `viewBox`. Logos render at fixed heights (22 / 60
 * px), so only the ratio is needed to size the `<img>` and reserve
 * horizontal space — the rendered width is `Math.round(height *
 * ratio)` at the call site.
 *
 * Generated by {@link run}, written to `public/logos/mono/manifest.json`,
 * and imported as a JSON module by the SSR loader.
 */
export type Manifest = Record<string, number>

/**
 * Generate normalized monochrome logo SVGs from `public/logos/` into
 * `public/logos/mono/`, plus a `manifest.json` mapping each slug to
 * its aspect ratio.
 *
 * Every committed source becomes one normalized output; slugs with no
 * source are silently absent (the homepage falls back to a plain-text
 * label). Output dir is wiped each run so removed sources don't
 * linger.
 *
 * Pure file-IO — no KV, no edge cache, no network. The CI workflow
 * commits the result back to the repo and Cloudflare's static asset
 * pipeline serves them at `/logos/mono/<slug>.svg`.
 */
export async function run(): Promise<void> {
  const entries = await fs.readdir(sourceDir, { withFileTypes: true })
  await fs.rm(outputDir, { recursive: true, force: true })
  await fs.mkdir(outputDir, { recursive: true })

  const manifest: Manifest = {}
  for (const entry of entries) {
    if (!entry.isFile() || !entry.name.endsWith('.svg')) continue
    const slug = entry.name.slice(0, -'.svg'.length)
    const bytes = await fs.readFile(path.join(sourceDir, entry.name), 'utf-8')
    let transformed: string
    try {
      transformed = await Svg.transform(bytes)
    } catch (error) {
      // unparseable / un-rasterizable source SVG — log + skip so one
      // bad input doesn't sink the whole run.
      console.error('logo SVG transform failed:', slug, error)
      continue
    }
    const box = parseViewBox(transformed)
    if (!box) {
      console.error('logo viewBox parse failed:', slug)
      continue
    }
    manifest[slug] = box.width / box.height
    await fs.writeFile(path.join(outputDir, `${slug}.svg`), transformed, 'utf-8')
  }

  // sorted-by-key for stable diffs across runs
  const sorted: Manifest = {}
  for (const slug of Object.keys(manifest).sort()) sorted[slug] = manifest[slug]!
  await fs.writeFile(manifestPath, `${JSON.stringify(sorted, null, 2)}\n`, 'utf-8')
}

/**
 * Pull width + height out of an SVG's `viewBox` (or `width`/`height`
 * attributes as a fallback). Returns `null` when no usable size can
 * be recovered. Regex-based — a full XML parser is overkill for the
 * SVGO-cleaned bytes {@link Svg.transform} emits.
 */
function parseViewBox(svg: string): { width: number; height: number } | null {
  const viewBox = svg.match(
    /\bviewBox\s*=\s*["']\s*([-\d.eE+]+)\s+([-\d.eE+]+)\s+([-\d.eE+]+)\s+([-\d.eE+]+)\s*["']/,
  )
  if (viewBox) {
    const width = Number(viewBox[3])
    const height = Number(viewBox[4])
    if (width > 0 && height > 0) return { width, height }
  }
  const w = svg.match(/<svg\b[^>]*\bwidth\s*=\s*["']\s*([\d.]+)/)?.[1]
  const h = svg.match(/<svg\b[^>]*\bheight\s*=\s*["']\s*([\d.]+)/)?.[1]
  if (w && h) {
    const width = Number(w)
    const height = Number(h)
    if (width > 0 && height > 0) return { width, height }
  }
  return null
}
