import * as Sync from '../worker/sync'
import * as Utils from './lib/utils'

/**
 * Seed local KV (or, with `WRANGLER_REMOTE=true`, production KV) with
 * stars / downloads / sponsors — every cron-driven source the
 * homepage reads.
 *
 * Logo bytes are static files generated by `pnpm gen:logos` (output
 * in `public/logo/`). They aren't part of this sync.
 *
 * Blocks until the sync completes (or throws on partial failure).
 */
await Utils.withEnv(async (env) => {
  await Sync.runAll(env)
})
